export const marvelData = [

    {
    name: "Beast",
    dataType: "char",
    imageL: "images/marvel/beast-200.png",
    imageM: "images/marvel/beast-100.png",
    imageS: "images/marvel/beast-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "10",
    cunning: "12",
    charisma: "8",
    cume: "30"
    },
    {
    name: "Black Panther",
    dataType: "char",
    imageL: "images/marvel/tchalla-200.png",
    imageM: "images/marvel/tchalla-100.png",
    imageS: "images/marvel/tchalla-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "9",
    cunning: "7",
    charisma: "12",
    cume: "28"
    },
    {
    name: "Bishop",
    dataType: "char",
    imageL: "images/marvel/bishop-200.png",
    imageM: "images/marvel/bishop-100.png",
    imageS: "images/marvel/bishop-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "6",
    cunning: "11",
    charisma: "7",
    cume: "24"
    },
    {
    name: "Cyclops",
    dataType: "char",
    imageL: "images/marvel/cyclops-200.png",
    imageM: "images/marvel/cyclops-100.png",
    imageS: "images/marvel/cyclops-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "5",
    cunning: "6",
    charisma: "11",
    cume: "22"
    },
    {
    name: "Colossus",
    dataType: "char",
    imageL: "images/marvel/colossus-200.png",
    imageM: "images/marvel/colossus-100.png",
    imageS: "images/marvel/colossus-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "12",
    cunning: "1",
    charisma: "9",
    cume: "22"
    },
    {
    name: "Daredevil",
    dataType: "char",
    imageL: "images/marvel/daredevil-200.png",
    imageM: "images/marvel/daredevil-100.png",
    imageS: "images/marvel/daredevil-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "12",
    power: "1",
    cunning: "10",
    charisma: "10",
    cume: "21"
    },
    {
    name: "Jessica Jones",
    dataType: "char",
    imageL: "images/marvel/jessica-200.png",
    imageM: "images/marvel/jessica-100.png",
    imageS: "images/marvel/jessica-50.png",
    pronouns:{they: "she", them: "her", their: "hers", theirs: "hers", themself: "herself"},
    power: "7",
    cunning: "9",
    charisma: "4",
    cume: "20"
    },
    {
    name: "Wolverine",
    dataType: "char",
    imageL: "images/marvel/logan-200.png",
    imageM: "images/marvel/logan-100.png",
    imageS: "images/marvel/logan-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "11",
    cunning: "4",
    charisma: "3",
    cume: "18"
    },
    {
    name: "Okoye",
    dataType: "char",
    imageL: "images/marvel/okoye-200.png",
    imageM: "images/marvel/okoye-100.png",
    imageS: "images/marvel/okoye-50.png",
    pronouns:{they: "she", them: "her", their: "hers", theirs: "hers", themself: "herself"},
    power: "2",
    cunning: "5",
    charisma: "9",
    cume: "16"
    },
    {
    name: "Deadpool",
    dataType: "char",
    imageL: "images/marvel/deadpool-200.png",
    imageM: "images/marvel/deadpool-100.png",
    imageS: "images/marvel/deadpool-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "4",
    cunning: "3",
    charisma: "6",
    cume: "13"
    },
    {
    name: "Punisher",
    dataType: "char",
    imageL: "images/marvel/punisher-200.png",
    imageM: "images/marvel/punisher-100.png",
    imageS: "images/marvel/punisher-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "3",
    cunning: "8",
    charisma: "1",
    cume: "12"
    },
    {
    name: "Ghostrider",
    dataType: "char",
    imageL: "images/marvel/blaze-200.png",
    imageM: "images/marvel/blaze-100.png",
    imageS: "images/marvel/blaze-50.png",
    pronouns:{they: "he", them: "him", their: "him", theirs: "his", themself: "himself"},
    power: "8",
    cunning: "2",
    charisma: "2",
    cume: "12"
    }
]